const AirlinesMapping = {
  AA: { name: "American Airlines", code: "AA", logo: "https://content.airhex.com/content/logos/airlines_AA_200_200_r.png" },
  DL: { name: "Delta Air Lines", code: "DL", logo: "https://content.airhex.com/content/logos/airlines_DL_200_200_r.png" },
  UA: { name: "United Airlines", code: "UA", logo: "https://content.airhex.com/content/logos/airlines_UA_200_200_r.png" },
  WN: { name: "Southwest Airlines", code: "WN", logo: "https://content.airhex.com/content/logos/airlines_WN_200_200_r.png" },
  B6: { name: "JetBlue Airways", code: "B6", logo: "https://content.airhex.com/content/logos/airlines_B6_200_200_r.png" },
  F9: { name: "Frontier Airlines", code: "F9", logo: "https://content.airhex.com/content/logos/airlines_F9_200_200_r.png" },

  FR: { name: "Ryanair", code: "FR", logo: "https://content.airhex.com/content/logos/airlines_FR_200_200_r.png" },
  LH: { name: "Lufthansa", code: "LH", logo: "https://content.airhex.com/content/logos/airlines_LH_200_200_r.png" },
  U2: { name: "easyJet", code: "U2", logo: "https://content.airhex.com/content/logos/airlines_U2_200_200_r.png" },
  AF: { name: "Air France", code: "AF", logo: "https://content.airhex.com/content/logos/airlines_AF_200_200_r.png" },
  KL: { name: "KLM", code: "KL", logo: "https://content.airhex.com/content/logos/airlines_KL_200_200_r.png" },

  "6E": { name: "IndiGo", code: "6E", logo: "https://content.airhex.com/content/logos/airlines_6E_200_200_r.png" },
  AI: { name: "Air India", code: "AI", logo: "https://content.airhex.com/content/logos/airlines_AI_200_200_r.png" },
  CZ: { name: "China Southern Airlines", code: "CZ", logo: "https://content.airhex.com/content/logos/airlines_CZ_200_200_r.png" },
  MU: { name: "China Eastern Airlines", code: "MU", logo: "https://content.airhex.com/content/logos/airlines_MU_200_200_r.png" },
  CA: { name: "Air China", code: "CA", logo: "https://content.airhex.com/content/logos/airlines_CA_200_200_r.png" },
  UL: { name: "SriLankan Airlines", code: "UL", logo: "https://content.airhex.com/content/logos/airlines_UL_200_200_r.png" },
  WY: { name: "Oman Air", code: "WY", logo: "https://content.airhex.com/content/logos/airlines_WY_200_200_r.png" },
  KC: { name: "Air Astana", code: "KC", logo: "https://content.airhex.com/content/logos/airlines_KC_200_200_r.png" },
  HR: { name: "Hahn Air", code: "HR", logo: "https://content.airhex.com/content/logos/airlines_HR_200_200_r.png" },

  TK: { name: "Turkish Airlines", code: "TK", logo: "https://content.airhex.com/content/logos/airlines_TK_200_200_r.png" },
  EK: { name: "Emirates", code: "EK", logo: "https://content.airhex.com/content/logos/airlines_EK_200_200_r.png" },
  QR: { name: "Qatar Airways", code: "QR", logo: "https://content.airhex.com/content/logos/airlines_QR_200_200_r.png" },
  SQ: { name: "Singapore Airlines", code: "SQ", logo: "https://content.airhex.com/content/logos/airlines_SQ_200_200_r.png" },

  LA: { name: "LATAM Airlines", code: "LA", logo: "https://content.airhex.com/content/logos/airlines_LA_200_200_r.png" },
  AS: { name: "Alaska Airlines", code: "AS", logo: "https://content.airhex.com/content/logos/airlines_AS_200_200_r.png" },
  W6: { name: "Wizz Air", code: "W6", logo: "https://content.airhex.com/content/logos/airlines_W6_200_200_r.png" },
  G3: { name: "Gol Linhas Aéreas", code: "G3", logo: "https://content.airhex.com/content/logos/airlines_G3_200_200_r.png" },

  BA: { name: "British Airways", code: "BA", logo: "https://content.airhex.com/content/logos/airlines_BA_200_200_r.png" },
  CX: { name: "Cathay Pacific", code: "CX", logo: "https://content.airhex.com/content/logos/airlines_CX_200_200_r.png" },
  EY: { name: "Etihad Airways", code: "EY", logo: "https://content.airhex.com/content/logos/airlines_EY_200_200_r.png" },
  MH: { name: "Malaysia Airlines", code: "MH", logo: "https://content.airhex.com/content/logos/airlines_MH_200_200_r.png" },
  NZ: { name: "Air New Zealand", code: "NZ", logo: "https://content.airhex.com/content/logos/airlines_NZ_200_200_r.png" },
  QF: { name: "Qantas", code: "QF", logo: "https://content.airhex.com/content/logos/airlines_QF_200_200_r.png" },
  JL: { name: "Japan Airlines", code: "JL", logo: "https://content.airhex.com/content/logos/airlines_JL_200_200_r.png" },
  AC: { name: "Air Canada", code: "AC", logo: "https://content.airhex.com/content/logos/airlines_AC_200_200_r.png" },
  AZ: { name: "Alitalia", code: "AZ", logo: "https://content.airhex.com/content/logos/airlines_AZ_200_200_r.png" },
  TG: { name: "Thai Airways International", code: "TG", logo: "https://content.airhex.com/content/logos/airlines_TG_200_200_r.png" },
  BR: { name: "EVA Air", code: "BR", logo: "https://content.airhex.com/content/logos/airlines_BR_200_200_r.png" },
  VA: { name: "Virgin Australia", code: "VA", logo: "https://content.airhex.com/content/logos/airlines_VA_200_200_r.png" },
  IB: { name: "Iberia", code: "IB", logo: "https://content.airhex.com/content/logos/airlines_IB_200_200_r.png" },
  SK: { name: "Scandinavian Airlines", code: "SK", logo: "https://content.airhex.com/content/logos/airlines_SK_200_200_r.png" },
  LX: { name: "SWISS", code: "LX", logo: "https://content.airhex.com/content/logos/airlines_LX_200_200_r.png" },
  KL: { name: "KLM Royal Dutch Airlines", code: "KL", logo: "https://content.airhex.com/content/logos/airlines_KL_200_200_r.png" },
  VN: { name: "Vietnam Airlines", code: "VN", logo: "https://content.airhex.com/content/logos/airlines_VN_200_200_r.png" },
  LX: { name: "SWISS International Air Lines", code: "LX", logo: "https://content.airhex.com/content/logos/airlines_LX_200_200_r.png" },
  KL: { name: "KLM", code: "KL", logo: "https://content.airhex.com/content/logos/airlines_KL_200_200_r.png" },
  ET: { name: "Ethiopian Airlines", code: "ET", logo: "https://content.airhex.com/content/logos/airlines_ET_200_200_r.png" },
  GA: { name: "Garuda Indonesia", code: "GA", logo: "https://content.airhex.com/content/logos/airlines_GA_200_200_r.png" },
  QV: { name: "Cebu Pacific", code: "QV", logo: "https://content.airhex.com/content/logos/airlines_QV_200_200_r.png" },
  NH: { name: "All Nippon Airways", code: "NH", logo: "https://content.airhex.com/content/logos/airlines_NH_200_200_r.png" },
  S7: { name: "S7 Airlines", code: "S7", logo: "https://content.airhex.com/content/logos/airlines_S7_200_200_r.png" },
  SU: { name: "Aeroflot", code: "SU", logo: "https://content.airhex.com/content/logos/airlines_SU_200_200_r.png" },
  GP: { name: "APG Airlines", code: "GP", logo: "https://content.airhex.com/content/logos/airlines_GP_200_200_r.png" },
  W2: { name: "FlexFlight", code: "W2", logo: "https://content.airhex.com/content/logos/airlines_W2_200_200_r.png" },
  HA: { name: "Hawaiian Airlines", code: "HA", logo: "https://content.airhex.com/content/logos/airlines_HA_200_200_r.png" },
  NK: { name: "Spirit Airlines", code: "NK", logo: "https://content.airhex.com/content/logos/airlines_NK_200_200_r.png" },
  TP: { name: "TAP Air Portugal", code: "TP", logo: "https://content.airhex.com/content/logos/airlines_TP_200_200_r.png" },
  FI: { name: "Icelandair", code: "FI", logo: "https://content.airhex.com/content/logos/airlines_FI_200_200_r.png" },
  "6X": { name: "Air Odisha", code: "6X", logo: "https://content.airhex.com/content/logos/airlines_6X_200_200_r.png" },
  KE: { name: "Korean Air", code: "KE", logo: "https://content.airhex.com/content/logos/airlines_KE_200_200_r.png" },
  WS: { name: "WestJet", code: "WS", logo: "https://content.airhex.com/content/logos/airlines_WS_200_200_r.png" },
  PR: { name: "Philippine Airlines", code: "PR", logo: "https://content.airhex.com/content/logos/airlines_PR_200_200_r.png" },
  OZ: { name: "Asiana Airlines", code: "OZ", logo: "https://content.airhex.com/content/logos/airlines_OZ_200_200_r.png" },
  LO: { name: "LOT Polish Airlines", code: "LO", logo: "https://content.airhex.com/content/logos/airlines_LO_200_200_r.png" },
  DE: { name: "Condor", code: "DE", logo: "https://content.airhex.com/content/logos/airlines_DE_200_200_r.png" },
  UX: { name: "Air Europa", code: "UX", logo: "https://content.airhex.com/content/logos/airlines_UX_200_200_r.png" },
  JU: { name: "Air Serbia", code: "JU", logo: "https://content.airhex.com/content/logos/airlines_JU_200_200_r.png" },
  TU: { name: "Tunisair Airline", code: "TU", logo: "https://content.airhex.com/content/logos/airlines_TU_200_200_r.png" },
  VY: { name: "Vueling Airlines", code: "VY", logo: "https://content.airhex.com/content/logos/airlines_VY_200_200_r.png" },
  PC: { name: "Pegasus Airlines", code: "PC", logo: "https://content.airhex.com/content/logos/airlines_PC_200_200_r.png" },
  LG: { name: "Luxair Airline", code: "LG", logo: "https://content.airhex.com/content/logos/airlines_LG_200_200_r.png" },
  BT: { name: "Air Baltic", code: "BT", logo: "https://content.airhex.com/content/logos/airlines_BT_200_200_r.png" },
  GQ: { name: "SKY express", code: "GQ", logo: "https://content.airhex.com/content/logos/airlines_GQ_200_200_r.png" },
  V7: { name: "Volotea Airline", code: "V7", logo: "https://content.airhex.com/content/logos/airlines_V7_200_200_r.png" },
  EI: { name: "Aer Lingus", code: "EI", logo: "https://content.airhex.com/content/logos/airlines_EI_200_200_r.png" },
  "3U": { name: "Sichuan Airlines", code: "3U", logo: "https://content.airhex.com/content/logos/airlines_3U_200_200_r.png" },
  MF: { name: "Xiamen Airlines", code: "MF", logo: "https://content.airhex.com/content/logos/airlines_MF_200_200_r.png" },
  HU: { name: "Hainan Airlines", code: "HU", logo: "https://content.airhex.com/content/logos/airlines_HU_200_200_r.png" },
  SC: { name: "Shandong Airlines", code: "SC", logo: "https://content.airhex.com/content/logos/airlines_SC_200_200_r.png" },
  "7C": { name: "Jeju Air", code: "7C", logo: "https://content.airhex.com/content/logos/airlines_7C_200_200_r.png" },
  TW: { name: "T'way Air", code: "TW", logo: "https://content.airhex.com/content/logos/airlines_TW_200_200_r.png" },
  XY: { name: "Flynas", code: "XY", logo: "https://content.airhex.com/content/logos/airlines_XY_200_200_r.png" },
  FZ: { name: "Flydubai", code: "FZ", logo: "https://content.airhex.com/content/logos/airlines_FZ_200_200_r.png" },
  SV: { name: "SAUDIA", code: "SV", logo: "https://content.airhex.com/content/logos/airlines_SV_200_200_r.png" },
  F3: { name: "Flyadeal Airline", code: "F3", logo: "https://content.airhex.com/content/logos/airlines_F3_200_200_r.png" },
  RJ: { name: "Royal Jordanian", code: "RJ", logo: "https://content.airhex.com/content/logos/airlines_RJ_200_200_r.png" },
  GF: { name: "Gulf Air", code: "GF", logo: "https://content.airhex.com/content/logos/airlines_GF_200_200_r.png" },
  KU: { name: "Kuwait Airways", code: "KU", logo: "https://content.airhex.com/content/logos/airlines_KU_200_200_r.png" },
};

export default AirlinesMapping;
