export const statesOfIndia = [
    "Jammu & Kashmir",
    "Himachal Pradesh",
    "Uttrakhand",
    "Punjab",
    "Haryana",
    "Delhi",
    "Uttar Pradesh",
    "Rajasthan",
    "Bihar",
    "Madhya Pradesh",
    "Assam",
    "West Bengal",
    "Oddisha",
    "Jharkhand",
    "Chattisgarh",
    "Maharashtra",
    "Andhra Pradesh",
    "Telegana",
    "Karnataka",
    "Kerala",
    "Tamil Nadu",
];
