name: Deploy Marketing

on:
  push:
    branches:
      - main   # deploy on main branch pushes
    paths:
      - 'packages/marketing/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Deploy to S3
        uses: aws-actions/s3-sync@v1
        with:
          args: --delete --cache-control max-age=31536000,public
        env:
          AWS_S3_BUCKET: ${{ secrets.MFE_MARKETING_CONTAINER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}  # change if needed
          SOURCE_DIR: dist         # or build

      - name: Upload remoteEntry.js (no cache)
        run: |
          aws s3 cp dist/remoteEntry.js s3://${{ secrets.MFE_MARKETING_CONTAINER }}/remoteEntry.js \
            --cache-control max-age=0,no-cache,no-store,must-revalidate
        env:
          AWS_S3_BUCKET: ${{ secrets.MFE_MARKETING_CONTAINER }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.MARKETING_DISTRIBUTE_ID }} --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
